"""
AI Weekly Newsletter — draft generation only.

Generates content with Claude for contacts flagged 'newsletter' in the DigiGrowth OS CRM.
Delivery is unresolved: this used to send via GHL's conversations email API, but Dylan no
longer uses GHL and nothing has replaced it. See apptset-agent/.claude/skills/newsletter/SKILL.md
("Send Mode — currently disabled") before wiring up a new send path.

Usage:
  python newsletter.py --preview   # generate draft + save to newsletter_draft.json (no send)
"""

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

import anthropic
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent.parent / "shared"))
from github_sync import push_file

load_dotenv()

DRAFT_FILE = Path(__file__).parent / "newsletter_draft.json"


# ── Content generation ────────────────────────────────────────────────────────

def generate_content(config):
    """Return (subject, html_body) generated by Claude.

    The HTML body uses {{first_name}} and {{business_name}} as placeholders
    that are replaced per-contact at send time.
    """
    client       = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY", ""))
    topic_hint   = config.get("newsletter", {}).get("topic_hint", "AI client acquisition for mobile and in-home veterinary practices")
    from_name    = config.get("newsletter", {}).get("from_name", "Dylan | Digigrowth")
    booking_link = config.get("newsletter", {}).get("booking_link", "")
    week_str     = date.today().strftime("%B %d, %Y")

    prompt = f"""\
Write a short weekly email newsletter for owners of independent mobile and in-home veterinary practices from {from_name}.
Topic this week: {topic_hint}
Week of: {week_str}

Use {{{{first_name}}}} where you address the reader by name and {{{{business_name}}}} where you reference their practice.
These are literal placeholders — include them exactly as shown.

Structure (in order):
1. Subject line — specific, curiosity-driven, under 60 chars, no spam words
2. Opening — "Hey {{{{first_name}}}}," then 1-2 sentences on a real pain point or surprising stat about AI adoption for mobile/in-home veterinary practices
3. Main tip — ONE actionable insight about using AI for client acquisition (3-5 sentences). Be specific and concrete.
4. CTA — "Want me to put together a custom AI + marketing plan for {{{{business_name}}}}? Book a quick discovery call → {booking_link if booking_link else '[BOOKING_LINK]'}"
6. Sign-off — casual, from {from_name}
7. Footer — plain-text unsubscribe note at the very bottom

Tone: direct, friendly, like a trusted friend who knows AI and marketing. No hype, no buzzwords.
Total reading time: under 90 seconds.

Output ONLY valid JSON — no markdown, no code fences:
{{"subject": "...", "html": "..."}}

The "html" value must be a self-contained HTML fragment (no <!DOCTYPE>, no <html>/<head>).
Use a centered div with max-width 600px, font-family sans-serif, line-height 1.6.
Inline all styles. Keep {{{{first_name}}}} and {{{{business_name}}}} as literal strings in the HTML.\
"""

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=2500,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text.strip()

    if raw.startswith("```"):
        parts = raw.split("```")
        raw   = parts[1].lstrip("json").strip() if len(parts) > 1 else raw

    parsed = json.loads(raw)
    return parsed["subject"], parsed["html"]


# ── Draft save ────────────────────────────────────────────────────────────────

def draft_newsletter(config):
    """Generate content and save to newsletter_draft.json. Does not send."""
    print("📰 Newsletter: generating content with Claude...")
    subject, html_body = generate_content(config)
    print(f"  ✅ Subject: {subject}")

    DRAFT_FILE.write_text(json.dumps({"subject": subject, "html": html_body}, indent=2))
    print(f"  ✅ Draft saved to {DRAFT_FILE}")
    push_file(str(DRAFT_FILE))
    return subject, html_body


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="DigiGrowth weekly newsletter (draft only)")
    parser.add_argument("--preview", action="store_true", help="Generate draft only, save to newsletter_draft.json")
    args = parser.parse_args()

    with open(Path(__file__).parent / "config.json") as f:
        config = json.load(f)

    draft_newsletter(config)
