"""
Read-only Calendly integration for response_ai.py's check_availability
tool — looks up a client's REAL open time slots via Calendly's API so the
agent proposes times that are actually open instead of guessing blind.

Auth is a Calendly Personal Access Token the client generates from their
own Calendly account (Integrations & Apps -> API & Webhooks -> Generate New
Token) — or Dylan's, once added as an admin on that client's account — and
pastes into their Marketing Setup (client_marketing_config.calendly_api_token).
Same "one credential per client, pasted in" pattern as the Gmail refresh
token.

Deliberately read-only: Calendly's public API has no endpoint to create a
CONFIRMED booking on someone else's behalf — an invitee always has to
complete the scheduling flow on Calendly's own page. Booking itself still
happens exactly as it always has in this system (routers/appointments.py's
create_appointment_row, called from response_ai.py's propose_appointment
tool) — this module just makes that a well-informed choice of time instead
of a blind guess, per confirmed scope (2026-09-14): check real availability,
still book internally.
"""
from datetime import datetime, timedelta, timezone

import httpx

_API_BASE = "https://api.calendly.com"
_CHUNK_DAYS = 7  # Calendly caps a single query window to 7 days


def _headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def _raise_with_context(resp: httpx.Response) -> None:
    """httpx's default error message on a 403 is just the status line —
    unhelpful for the one failure mode we've actually hit in practice: a
    token generated with restricted OAuth scopes (e.g. missing users:read)
    instead of a plain Personal Access Token, which Calendly happily
    accepts as "valid" right up until the first API call. Surface the
    response body so the real reason (e.g. "Insufficient scope") ends up in
    logs instead of a bare "403 Forbidden"."""
    if resp.status_code == 403:
        raise RuntimeError(
            f"Calendly returned 403 Forbidden: {resp.text.strip()[:300]} — the token likely lacks "
            "read permissions. Regenerate it from Calendly's own account (not a third-party OAuth "
            "connection) via Integrations & Apps -> API & Webhooks -> Generate New Token."
        )
    resp.raise_for_status()


async def _get_matching_event_type(http: httpx.AsyncClient, token: str, scheduling_url: str) -> dict | None:
    """Resolves the client's configured scheduling_url to its Calendly
    event type object. Deliberately never guesses "whichever event type
    comes back first" — a Personal Access Token generated by an admin who
    manages multiple people's Calendly (Dylan's own real setup: one token
    sees both his own event types and a client's, since he's a team member
    on their account) can see OTHER people's event types too. "First
    result" happened to be the right one when this was first tested, purely
    by luck of Calendly's ordering that day — the next admin-managed client
    added, or a reordering on Calendly's side, could just as easily point
    this at someone else's calendar entirely. Matching on the exact
    scheduling_url the admin configured (their real public booking link,
    something they can visually verify) is the only safe way to do this."""
    me = await http.get(f"{_API_BASE}/users/me", headers=_headers(token))
    _raise_with_context(me)
    user_uri = me.json()["resource"]["uri"]

    target = scheduling_url.strip().rstrip("/")
    page_token = None
    while True:
        params = {"user": user_uri, "active": "true", "count": 100}
        if page_token:
            params["page_token"] = page_token
        resp = await http.get(f"{_API_BASE}/event_types", headers=_headers(token), params=params)
        _raise_with_context(resp)
        data = resp.json()
        for item in data.get("collection", []):
            if item.get("scheduling_url", "").rstrip("/") == target:
                return item
        page_token = (data.get("pagination") or {}).get("next_page_token")
        if not page_token:
            return None


async def find_earliest_available_times(
    token: str, scheduling_url: str, start_iso: str, max_days: int = 30,
) -> list[dict]:
    """Searches forward from start_iso in 7-day windows (Calendly's own
    per-query cap) until it finds real open slots or exhausts max_days,
    returning the first day's worth found. A newly-active event type often
    has nothing open for the first week or two (the business hasn't set
    availability that far out yet, or the near term is already booked) —
    only ever checking one exact day and giving up the moment it's empty
    means the agent asks the lead to guess-and-check days one at a time
    instead of just finding the real earliest opening itself. Returns
    Calendly's raw slot objects (each has start_time in UTC) — empty list
    if genuinely nothing's open in the whole window, or the scheduling_url
    doesn't match any event type this token can see."""
    async with httpx.AsyncClient(timeout=10) as http:
        event_type = await _get_matching_event_type(http, token, scheduling_url)
        if not event_type:
            return []

        start = datetime.fromisoformat(start_iso.replace("Z", "+00:00"))
        if start.tzinfo is None:
            start = start.replace(tzinfo=timezone.utc)
        horizon = start + timedelta(days=max_days)

        window_start = start
        while window_start < horizon:
            window_end = min(window_start + timedelta(days=_CHUNK_DAYS), horizon)
            resp = await http.get(
                f"{_API_BASE}/event_type_available_times",
                headers=_headers(token),
                params={
                    "event_type": event_type["uri"],
                    "start_time": window_start.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "end_time": window_end.strftime("%Y-%m-%dT%H:%M:%SZ"),
                },
            )
            _raise_with_context(resp)
            slots = resp.json().get("collection", [])
            if slots:
                return slots
            window_start = window_end
        return []


async def find_slot_scheduling_url(
    token: str, scheduling_url: str, date_str: str, time_str: str, tz,
) -> str | None:
    """Looks up the direct, single-slot Calendly booking link for one
    exact local date/time (e.g. "2026-09-17" / "14:00") — each slot in
    Calendly's own available-times response already carries its own
    scheduling_url pointing straight at that time, one tap from a
    confirmed booking, no re-picking a day on Calendly's page needed.
    Used by propose_appointment so the agent can text the lead something
    that actually finishes the booking, instead of just logging a
    trusted-verbal-agreement row internally (Calendly's API still has no
    way to create the confirmed booking itself — the lead has to be the
    one to complete it). Returns None if the slot can't be re-matched
    (already taken, clock drift, bad date/time) — caller falls back to
    the internal-only booking message in that case."""
    async with httpx.AsyncClient(timeout=10) as http:
        event_type = await _get_matching_event_type(http, token, scheduling_url)
        if not event_type:
            return None

        local_day_start = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=tz)
        local_day_end = local_day_start + timedelta(days=1)
        resp = await http.get(
            f"{_API_BASE}/event_type_available_times",
            headers=_headers(token),
            params={
                "event_type": event_type["uri"],
                "start_time": local_day_start.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "end_time": local_day_end.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            },
        )
        _raise_with_context(resp)
        slots = resp.json().get("collection", [])

        target = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M").replace(tzinfo=tz)
        for s in slots:
            slot_local = datetime.fromisoformat(s["start_time"].replace("Z", "+00:00")).astimezone(tz)
            if abs((slot_local - target).total_seconds()) < 60:
                return s.get("scheduling_url")
        return None
